name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-pdf
      - run: mkdocs gh-deploy --force
      


# name: ci

# on:
#   push:
#     branches:
#       - master
#       - main

# permissions:
#   contents: write

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.x

#       # Install system dependencies for WeasyPrint (required for mkdocs-pdf plugin)
#       - name: Install system dependencies for WeasyPrint
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y \
#             libcairo2 \
#             libcairo2-dev \
#             libpango1.0-0 \
#             libpango1.0-dev \
#             libgdk-pixbuf2.0-0 \
#             libgdk-pixbuf2.0-dev \
#             python3-cairocffi \
#             libffi-dev

#       # Cache Python dependencies
#       - name: Cache Python dependencies
#         uses: actions/cache@v2
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-python-

#       # Install Python dependencies
#       - name: Install dependencies
#         run: |
#           pip install --upgrade pip
#           pip install mkdocs-material
#           pip install mkdocs-pdf
#           pip install weasyprint

#       # Deploy the site to GitHub Pages
#       - name: Deploy to GitHub Pages
#         run: mkdocs gh-deploy --force
